stock/urls.py
from django.urls import path
from stock import views

app_name = 'stock'
urlpatterns = [
    #/stock/
    path('',views.StockModelView.as_view(), name='index'),
    #/stock/stockinfo/
    path('stockinfo/',views.StockInfo_List_View, name='stockinfo_list'),
    #/stock/stockinfo/<str:code>
    path('stockinfo/detail/<str:code_number>/',views.StockInfo_Detail_View, name='stockinfo_detail'),


    path('search/',views.Search_Info, name='search_info'),
    path('search/<str:stock_name>/<str:code_number>',views.Save_Favor, name='save_favor'),
    path('favor_detail/favor/<int:pk>',views.Delete_Favor, name='delete_favor'),

]

stocksite/urls.py
from django.contrib import admin
from django.urls import path, include
from stocksite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock/',include('stock.urls')),
    path('',views.HomeView.as_view(), name='home'),
]

stock/models.py
from django.db import models

# Create your models here.

class StockInfo(models.Model):
    name = models.CharField(max_length=100,null=False)
    code = models.CharField(max_length=6,null=False)

    class Meta:
        managed = False
        db_table = 'stock_stockinfo'

    def __str__(self):
        return self.name

stock/forms.py
from django import forms

class SearchKeywordForm(forms.Form):
    search_keyword = forms.CharField(max_length=100)

    def clean_search_keyword(self):
        data = self.cleaned_data['search_keyword']
        #check data
        return data

stock/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic import DetailView
from stock.models import StockInfo
from django.http  import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

#template
class StockModelView(TemplateView):
    template_name = 'stock/stockinfo_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model_list"] = ['StockInfo',]
        return context

#favor stock list view
from stock import django_crawler
def StockInfo_List_View(request):
    stockinfo_list = StockInfo.objects.all().order_by('id')
    context_list = []

    for stockinfo in stockinfo_list:
        temp_list = django_crawler.get_listinfo(stockinfo.code)
        context_list.append((temp_list))

    context = {
        'object_info_list' : context_list,
    }
    print('list')
    return render(request, 'stock/stockinfo_list.html', context)


#
import json
def StockInfo_Detail_View(request,code_number):

    stockinfo = get_object_or_404(StockInfo,code=code_number)

    
    detailinfo = django_crawler.get_all_detail_info(code_number)
    chartinfo = django_crawler.get_chart_info(code_number)
    chart_close_info = json.dumps(list(chartinfo.to_dict()['Close'].values()))
    chart_date_info = json.dumps(list(chartinfo.to_dict()['Date'].values()))
    print(chart_close_info)
    print(chart_date_info)
    
    context = {
        'stockinfo' : stockinfo,
        'detailinfo' : detailinfo,
        'deltaprice' : django_crawler.get_price_info(code_number),
        'chartcloseinfo': chart_close_info,
        'chartdateinfo': chart_date_info,
    }
    print('detail')
    return render(request,'stock/stockinfo_detail.html',context)


from stock.forms import SearchKeywordForm


#
def Search_Info(request):
    search_keyword_form = SearchKeywordForm(request.GET)
    kw_valid = False
    temp_list = []

    if search_keyword_form.is_valid():
        skw = search_keyword_form.cleaned_data['search_keyword']
        if len(skw) == 6 and skw.isdigit():
            kw_valid = True
            detail_info = django_crawler.get_all_detail_info(skw)
            list_info = django_crawler.get_listinfo(skw)
    else:
        skw = 'form_invalid'
    
    context = {
        'search_keyword' : skw,
        'keyword_valid' : kw_valid,
        'listinfo':list_info,
        'detailinfo': detail_info,
    }
    print('search')
    return render(request, 'stock/stockinfo_search_result.html', context)

#
def Save_Favor(request,stock_name,code_number):
    print('save')
    StockInfo.objects.create(name=stock_name, code=code_number)
    return HttpResponseRedirect(reverse('stock:stockinfo_detail', args=[code_number,]))

#
def Delete_Favor(request,pk):
    print('delete')
    StockInfo.objects.filter(pk=pk).delete()
    return HttpResponseRedirect(reverse('stock:stockinfo_list'))

stocksite/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView
from django.apps import apps
# Create your views here.

#template
class HomeView(TemplateView):
    template_name = 'cover.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['app_list'] = ['stock']
        return context

stock/templates/dashboard.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Dashboard Template · Bootstrap v5.0</title>

    <!-- Bootstrap core CSS -->
    {% load static %}

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">    
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <meta name="theme-color" content="#7952b3">

    <!--chart.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'templates/css/dashboard.css' %}" rel="stylesheet">

  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <form class="d-flex" action="{% url 'stock:search_info' %}" method="get">
    {% csrf_token %}
    {{form}}
    <input class="form-control me-2" name="search_keyword" type="search" placeholder="종목코드" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>

</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span> Main List</span>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'stock:index' %}">
              <span data-feather="home"></span>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
              <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
              </svg>
              Stock Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stock:stockinfo_list' %}">
              <span data-feather="list"></span>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
            </svg>
              Stock List
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="achieve"></span>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-flag" viewBox="0 0 16 16">
              <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001M14 1.221c-.22.078-.48.167-.766.255-.81.252-1.872.523-2.734.523-.886 0-1.592-.286-2.203-.534l-.008-.003C7.662 1.21 7.139 1 6.5 1c-.669 0-1.606.229-2.415.478A21.294 21.294 0 0 0 3 1.845v6.433c.22-.078.48-.167.766-.255C4.576 7.77 5.638 7.5 6.5 7.5c.847 0 1.548.28 2.158.525l.028.01C9.32 8.29 9.86 8.5 10.5 8.5c.668 0 1.606-.229 2.415-.478A21.317 21.317 0 0 0 14 7.655V1.222z"/>
              </svg>
              Achieve
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    {% block content %}
      
    {% endblock content %}


  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</body>
</html>

stock/templates/stock/stockinfo_detail.html
{% extends 'dashboard.html' %}

{% block content %}



    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="d-flex align-items-end"> 
          <h2>{{stockinfo.name}}</h2>
          &nbsp;&nbsp;{{stockinfo.code}}
          &nbsp;
            <!-- Button trigger modal -->
            <a class="btn btn-success" href="#" role="button" data-toggle="modal" data-target="#exampleModal">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-plus" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5V6H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V7H6a.5.5 0 0 1 0-1h1.5V4.5A.5.5 0 0 1 8 4z"/>
                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                </svg>
            관심목록제거 
            </a>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{stockinfo.name}}을 관심목록에서 제거하시겠습니까?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                    <button type="button"  onclick="location.href='{% url 'stock:delete_favor' stockinfo.id%}'" class="btn btn-success">관심목록 제거</button>
                </div>
                </div>
            </div>
            </div>


        </div>
        {% with detailinfo.0 as topinfo %}
        <div class="d-inline-flex  mb-2 mb-md-0">

          <div class="row">
            <div class="col-sm text-center" style="width:250px;">
              PER</br>
              {{ topinfo.0 }}
            </div>
            <div class="col-sm text-center">
              12M PER</br>
              {{topinfo.1}}
            </div>
            <div class="col-sm text-center">
              업종 PER</br>
              {{topinfo.2}}
            </div>
            <div class="col-sm text-center">
              PBR</br>
              {{topinfo.3}}
            </div>
            <div class="col-sm text-center">
              배당수익률</br>
              {{topinfo.4}}
            </div>
          </div>
        </div>
        {% endwith %}
      </div>
      
      <canvas class="my-3 w-50 border" id="myChart" width="900" height="380"></canvas>

      <script>
      var ctx = document.getElementById('myChart');
      
      var closedt = {{ chartcloseinfo|safe }};
      var dtdt = {{ chartdateinfo|safe }};
      var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: dtdt,
              datasets: [{
                  label: [1],
                  data: closedt,
                  borderWidth: 1
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true
                      }
                  }]
              }
          }
      });
      </script>


      <!-- 시세현황 -->

      <div class="p-4 p-md-2 mb-4 border-bottom text-white rounded bg-secondary "><h4>시세현황</h4></div>

      {% with detailinfo.1 as priceinfo %}
      <div class="table-responsive">
        <table class="table">
        <colgroup>
        <col class = "table-secondary" style="width: 23%;">
        <col >
        <col class = "table-secondary" style="width: 23%;">
        <col >
        </colgroup>
        <tbody>
        <tr>
        <th scope="row"><div>종가/ 전일대비</div></th>
        {% if deltaprice %}
        <td class = "text-end text-danger"> {{priceinfo.0}}</td>
        {% else %}
        <td class = "text-end text-primary"> {{priceinfo.0}}</td>
        {% endif %}
        <th scope="row"><div>거래량</div></th>
        <td class = "text-end"> {{priceinfo.1}} </td>
        </tr>
        <tr>
        <th scope="row"><div>52주.최고가/ 최저가 </div></th>
        <td class = "text-end"> {{priceinfo.2}} </td>
        <th scope="row"><div>거래대금<span>(억원)</span></div></th>
        <td class = "text-end"> {{priceinfo.3}} </td>
        </tr>
        <tr>
        <th scope="row"><div>수익률<span>(1M/ 3M/ 6M/ 1Y)</span></div></th>
        <td class = "text-end"> {{priceinfo.4}} </td>
        <th scope="row"><div>외국인 보유비중</div></th>
        <td class = "text-end"> {{priceinfo.5}} </td>
        </tr>
        <tr>

        <th scope="row">
            시가총액<span>(상장예정포함,억원)</span>
          </div>
        </th>
        <td class = "text-end"> {{priceinfo.6}} </td>
        <th scope="row"><div>베타<span>(1년)</span></div></th>
        <td class = "text-end"> {{priceinfo.7}} </td>
        </tr>
        <tr>
        <th scope="row"><div><!--<dl><dt>시가총액(보통주)</dt><dd>종가(보통주)*상장주식수(보통주)</dd></dl>-->
        시가총액<span>(보통주,억원)</span></div></th>
        <td class = "text-end"> {{priceinfo.8}} </td>
        <th scope="row"><div>액면가</div></th>
        <td class = "text-end"> {{priceinfo.9}} </td>
        </tr>
        <tr>
        <tr>
        <th scope="row"><div>발행주식수<span>(보통주/ 우선주)</span></div></th>
        <td class = "text-end"> {{priceinfo.10}} </td>
        <th scope="row">
          <div>
            유동주식수/비율<span>(보통주)</span>
          </div>
        </th>
        <td class = "text-end"> {{priceinfo.11}} </td>
        </tr>
        </tbody>
        </table>
      </div>
      {% endwith %}

      <!-- 실적이슈  -->
      <div class="p-4 p-md-2 mb-4 border-bottom text-white rounded bg-secondary "><h4 class=>실적이슈</h4></div>

      {% with detailinfo.2 as issueinfo %}
      <div class="table-responsive">
        <table class="table">
        <colgroup>
        <col >
        <col >
        <col >
        <col >
        </colgroup>
        <thead>
        <tr>
        <th class = "text-center" scope="col">잠정실적발표일</th>
        <th class = "text-center" scope="col">잠정실적<span class='stxt'>(영업이익,&nbsp;억원)</span></th>
        <th class = "text-center" scope="col">&nbsp;&nbsp;예상실적대비<span class='stxt'>(%)</span></th>
        <th class = "text-center" scope="col">&nbsp;&nbsp;전년동기대비<span class='stxt'>(%)</span></th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td class = "text-center">{{issueinfo.0}}</td>
        <td class = "text-center">{{issueinfo.1}}</td>
        <td class = "text-center">{{issueinfo.2}}</td>
        <td class = "text-center">{{issueinfo.3}}</td>
        </tr>
        </tbody>
        </table>
      </div>
      {% endwith %}


      <!-- 운용사별 보유현황-->
      <div class="p-4 p-md-2 mb-4 border-bottom text-white rounded bg-secondary"><h4>&nbsp;운용사별 보유현황</h4></div>

      {% with detailinfo.3 as managerinfo %}
      <div class="table-responsive">
        <table class="table">
        <colgroup>
        <col style="width: 25%;">
        <col >
        <col >
        <col >
        <col >
        </colgroup>
        <thead>
        <tr>
        <th scope="col">운용사명</th>
        <th scope="col">보유수량(천주)</th>
        <th scope="col">시가평가액(억원)</th>
        <th scope="col">상장주식수내비중(%)</th>
        <th scope="col">운용사내비중(%)</th>
        </tr>
        </thead>
        <tbody>
        {% for rows in managerinfo %}
          <tr>
          {% for row in rows %}
            {% if forloop.counter0 > 0 %}
              <td class="r">{{row}}</td>
            {% else %}
              <th scope="row">{{row}}</th>
            {% endif %}
          {% endfor %}
          </tr>
        {% endfor %}
        </tbody>
        </table>
      </div>
      {% endwith %}


      <div class="row">
        <div class="col">
        <!-- 주주현황 -->
        <div class="p-4 p-md-1 mb-4 border-bottom text-white rounded bg-secondary "><h4>&nbsp;주주 현황</h4></div>

        {% with detailinfo.4 as holderinfo %}
        <div class="table-responsive">
          <table class="table table-sm">
          <colgroup>
          <col style="width: 36%;">
          <col >
          <col >
          <col >
          </colgroup>
          <thead>
          <tr>
          <th scope="col">항목</th>
          <th scope="col">보통주</th>
          <th scope="col">지분율</th>
          <th scope="col">최종변동일</th>
          </tr>
          </thead>
          <tbody>
          {% for rows in holderinfo %}
            <tr>
            {% for row in rows %}
              {% if forloop.counter0 > 0 %}
                <td class="r">{{row}}</td>
              {% else %}
                <th scope="row">{{row}}</th>
              {% endif %}
            {% endfor %}
            </tr>
          {% endfor %}

          </tbody>
          </table>
        </div>
        {% endwith %}

        </div>
        <div class="col">
        <!-- 주주구분 현황 -->
        <div class="p-4 p-md-1 mb-4 border-bottom text-white rounded bg-secondary "><h4>&nbsp;주주구분 현황</h4></div>

        {% with detailinfo.5 as holderinfo %}
        <div class="table-responsive">
          <table class="table table-sm">
          <colgroup>
          <col style="width: 36%;">
          <col >
          <col >
          <col >
          </colgroup>
          <thead>
          <tr>
          <th scope="col">주주구분</th>
          <th scope="col">대표주주수</th>
          <th scope="col">보통주</th>
          <th scope="col">지분율</th>
          <th scope="col">최종변동일</th>
          </tr>
          </thead>
          <tbody>

          {% for rows in holderinfo %}
            <tr>
            {% for row in rows %}
              {% if forloop.counter0 > 0 %}
                <td class="r">{{row}}</td>
              {% else %}
                <th scope="row">{{row}}</th>
              {% endif %}
            {% endfor %}
            </tr>
          {% endfor %}
          </tbody>
          </table>
        </div>
        {% endwith %}


        </div>
      </div>
    </main>
    
{% endblock content %}

stock/templates/stock/stockinfo_home.html
{% extends "dashboard.html" %}
{% block content %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <h1>HOME</h1>
    </main>

{% endblock content %}

templates/cover.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Cover Page</title>

    <!-- Bootstrap core CSS -->

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'templates/css/cover.css' %}" rel="stylesheet">

  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Stock</h3>

      <nav class="nav nav-masthead navbar-light justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Stock List</a>
        <a class="nav-link" href="#">Data Base</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>Cover your page.</h1>
    <p class="lead">Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead"> 
      <a href="{% url 'stock:index' %}" class="btn btn-lg btn-secondary fw-bold border-white bg-black">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>


    
  </body>
</html>r